spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lingoor_db
    username: lingoor_admin
    password: lingoor_admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
server:
  servlet:
    context-path: /api