spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lingoor_db
      ?useSSL=false
      &allowPublicKeyRetrieval=true
      &serverTimezone=UTC
    username: lingoor_admin
    password: lingoor_admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: ${SecurityLogLevel:TRACE}
  pattern:
    console: ${LogPatternConsole:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
